Repository CWJ1222/Cobra_09, pull requests merged in 2024-12, with the labels that each got.

#14 feat:초기 스타일 설정 및 헤더 추가
  public/css/common.css
  public/css/header.css
  public/css/reset.css
  public/css/root.css
  public/img/pooh.png
  views/include/head.ejs
  views/include/header.ejs
  views/include/include.ejs
  views/index.ejs
  views/login.ejs
  views/profile.ejs
  views/signin.ejs
  views/signup.ejs
Labels: FE

#16 feat: 헤더, 라우팅 작업, 로고 교체
  controller/Cmain.js
  public/css/common.css
  public/css/header.css
  public/img/favicon.ico
  public/img/logo-title.png
  routes/index.js
  views/include/head.ejs
  views/include/header.ejs
  views/index.ejs
  views/purchase.ejs
  views/sell.ejs
Labels: FE

#19 feat: footer 초기 스타일
  public/css/footer.css
  views/include/footer.ejs
  views/index.ejs
Labels: FE

#20 feat: 로그인 기능 및 유효성 검사
  .prettierrc
  controller/Cauth.js
  public/css/common.css
  routes/auth.js
  views/include/header.ejs
  views/login.ejs
Labels: FE

#21 feat:회원가입 페이지
  controller/Cmember.js
  public/css/common.css
  views/login.ejs
  views/signup.ejs
  views/signupTest.ejs
Labels: FE

#25 Feat : 충돌 해결 완료
  .env
  app.js
  cobra.sql
  controller/Cauth.js
  controller/Chost.js
  controller/Cmain.js
  package-lock.json
  package.json
  routes/auth.js
  routes/host.js
  routes/product.js
  views/hostTest.ejs
  views/loginTest.ejs
Labels: BE

#26 Feature/kakao oauth
  .env
  app.js
  cobra.sql
  controller/Cauth.js
  controller/Chost.js
  models/User.js
Labels: BE

#28 feat:로그인,회원가입 임시 페이지 연결 테스트 완료
  .gitignore
  controller/Cauth.js
  public/img/oauthKakao.png
  views/login.ejs
  views/signup.ejs
Labels: FE

#29 feat : 구매페이지 주소 검색 api 추가
  controller/Chost.js
  views/buyForm.ejs
  views/include/header.ejs
Labels: BE

#32 feat: 로그인 페이지 View 개선 및 기능 추가
  public/css/common.css
  public/img/oauthKakao.png
  views/login.ejs
Labels: FE

#33 feat:구매 페이지 개선 및 기능 추가
  controller/Cpurchase.js
  public/css/common.css
  public/img/filter-all.png
  public/img/filter-books.png
  public/img/filter-clothes.png
  public/img/filter-electronics.png
  routes/purchase.js
  views/include/header.ejs
  views/purchase.ejs
  views/purchaseTest.ejs
Labels: FE

#34 feat: 카카오톡 나와의 채팅 메세지 발송하는 기능 추가
  app.js
  controller/Cauth.js
  routes/auth.js
  routes/host.js
Labels: BE

#39 fix: 구매 페이지 렌더링 문제 해결
  app.js
  controller/Cproduct.js
  views/include/header.ejs
  views/purchase.ejs
Labels: FE

#43 Feat: 백엔드 찜 기능 테스트를 위한 구매페이지 임시 화면
  controller/Cproduct.js
  routes/product.js
  views/purchase.ejs
Labels: FE

#46 Feat/wish list
  cobra.sql
  controller/Chost.js
  controller/Cmain.js
  routes/index.js
  views/hostTest.ejs
  views/include/header.ejs
  views/mypage.ejs
  views/sell.ejs
  views/wishlist.ejs
Labels: FE, BE

#47 CWJ/찜하기버튼과데이터전달,상품카드이미지 보이게 경로 수정,찜한상품 눌렀을 때css수정,찜한상품에서 물건구매창으로 연결되게
  controller/Cmain.js
  views/purchase.ejs
  views/wishlist.ejs
Labels: FE, BE

#48 feat: 로그인 여부에 따라 헤더 버튼 변경
  controller/Cauth.js
  controller/Chost.js
  controller/Cmain.js
  controller/Cproduct.js
  controller/Cpurchase.js
  views/include/header.ejs
Labels: FE, BE

#49 feat: 로그인 상태 코드 기반 에러 처리 구현 외
  controller/Cauth.js
  controller/Chost.js
  controller/Cmember.js
  views/include/header.ejs
  views/login.ejs
Labels: FE, BE

#50 Feat/homemain
  cobra.sql
  controller/Cmain.js
  models/index.js
  views/index.ejs
Labels: FE, BE

#52 CWJ/구매탭 카테고리별 상품 정렬기능 구현
  controller/Cproduct.js
  routes/product.js
  views/purchase.ejs
Labels: FE, BE

#53 feat: 회원가입 페이지 유효성 검사, 비밀번호 보기 숨기기, 스타일 개선
  public/css/common.css
  views/signup.ejs
Labels: FE

#57 feat : 구매등록 페이지 css 변경
  cobra.sql
  controller/Ccomment.js
  controller/Cpurchase.js
  views/buyForm copy.ejs
  views/buyForm.ejs
Labels: FE, BE

#58 fix: 헤더, 회원가입 에러 수정
  views/include/header.ejs
  views/login.ejs
Labels: FE

#59 feat : 답글 추가시 스크롤 이동
  views/buyForm.ejs
  views/login.ejs
Labels: FE, BE

#61 feat:대댓글 아이콘 추가(replyIcon)
  views/buyForm.ejs
Labels: FE

#62 feat : 대댓글 추가 기준 depth 이상 금지
  controller/Ccomment.js
  views/buyForm.ejs
  views/login.ejs
Labels: FE, BE

#63 fix: 구매 신청 페이지(buyForm), 헤더 문제 해결
  public/css/header.css
  views/buyForm.ejs
  views/include/header.ejs
  views/login.ejs
Labels: FE

#66 feat : 회원탈퇴시 카카오 연결 끊기 추가
  cobra.sql
  controller/Cauth.js
  controller/Ccomment.js
  controller/Cmain.js
  routes/comment.js
Labels: BE

#67 feat : 로그인 버그 수정
  controller/Cauth.js
Labels: BE

#64 style: 마이페이지 버튼 스타일 적용
  views/include/header.ejs
Labels: FE
